Divides the module into two parts (and more)
UCL-RITS/doctoral-programming-intro pull request #28
Opened 2021-11-09 17:36 UTC by dpshelio

This course is now going to be taught as two (consecutive) courses. This PR brings that in!

This is done by adding two sections on the main page and on the navbar
(content is now separated into two directories)

But it also brings some new stuff:
- Uses Jekyll remote-themes (to get updates directly from the theme)
- Updates to the latest version of jekyll
- Uses a new md parser (kramdown instead of redcap)
- pip packages should be also cached now (only the latex/pandoc stuff is missing now)

2021-11-09 18:16 UTC, matt-graham requested changes
Looks great in general. I've made a few small suggestions - mainly changing capitalization and adding a bit of formatting. The main thing I think needs potentially changing is that my understanding was that the `notebooks/060MatplotlibPyplot.ipynb` notebook should be part of the beginners course (as this is the new introductory notebook only covering the basics of using the `pyplot` interface) and so moved to the `01-beginner` subdirectory rather than `02-novice`? Based on our last in person meeting I think we'd said we would include a basic intro to Matplotlib in the beginners course, but cover the object oriented interface and more advanced usage in the second course.

2021-11-09 18:16 UTC, matt-graham commented on index.md
> +  - Creating packages
This seems to differ a bit from the split we have in the HackMD planning page inasmuch that I think the plan was to have a basic intro to Matplotlib in the beginner course as well as a further lesson on more advanced usage of Matplotlib in the follow up?

2021-11-09 18:16 UTC, matt-graham commented on index.md
>  title: An introduction to programming for research using python
```suggestion
title: An introduction to programming for research using Python
```

2021-11-09 18:16 UTC, matt-graham commented on 02-novice/index.md
> +This course introduces the basics of creating and interacting with scientific Python libraries such as numpy, scipy and matplotlib. If you are familiar with the basics of programming (variables, loop
```suggestion
This course introduces the basics of creating and interacting with scientific Python libraries such as [NumPy](https://numpy.org/, [SciPy](https://scipy.org/) and [Matplotlib](https://matplotlib.org/). If you are familiar with the basics of programming (variables, loops and functions) then this course offers you the next step – how to structure your code and organise it into modules.
```

2021-11-09 18:16 UTC, matt-graham commented on 02-novice/index.md
> +This is the second part of the Introduction to research programming with Python course
```suggestion
This is the second part of the *Introduction to research programming with Python* course
```

2021-11-09 18:16 UTC, matt-graham commented on 01-beginner/index.md
> +1. Use python from different interfaces
```suggestion
1. Use Python from different interfaces
```

2021-11-09 18:16 UTC, matt-graham commented on 01-beginner/index.md
> +This is the first part of the Introduction to research programming with Python course.
```suggestion
This is the first part of the *Introduction to research programming with Python* course.
```

2021-11-09 18:16 UTC, matt-graham commented on 01-beginner/index.md
> +it for research. It’s aimed to researchers that have no experience of
```suggestion
it for research. It’s aimed at researchers that have no experience of
```

2021-11-09 18:16 UTC, matt-graham commented on 01-beginner/index.md
> +This is the first part of the Introduction to research programming with Python course.
(putting this in italics I thinks makes it more obvious that the capitalization is because this is the course name)

2021-11-09 19:45 UTC, dpshelio commented on index.md
> +You should join us instead for [MPHYG021: Research Software Engineering with Python](http://github-pages.ucl.ac.uk/rsd-engineeringcourse/)
That was a remanent from when `MPHY0021` was `MPHYG001` - I never knew what the `G` was for :sweat_smile:

2021-11-10 09:17 UTC, matt-graham approved these changes

2021-11-10 10:20 UTC, merged